# General Settings
name: Jules Rosser
job_title: Android Engineer
email: julianrosser91@gmail.com
description: Android Engineer with four years professional experience architecting modern Android applications, with an expertise in Kotlin, MVVM, RxJava and Dagger.
avatar: https://julesssss.github.io/assets/images/profile_image.jpg
favicon:
twitter_handler:
analytics_code: # UA-XXXXXXX-2
disqus: # your_disqus_site

home_sidebar: About # String to show as "Home" at the sidebar. It was hardcoded.

# Social Accounts
social_networks:
-  { name: linkedin, url: 'https://www.linkedin.com/in/julianrosser91/' }
-  { name: github, url: 'https://github.com/Julesssss' }
-  { name: medium, url: 'https://medium.com/@julesrosser' }
-  { name: stack-overflow, url: 'https://stackoverflow.com/users/4160784' }

# Modules Settings
show_categories: 0
show_tags: 0
show_email: 1
show_rss: 0
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serving
url: "https://julesrosser.com"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag
